data: 'data/lcsts/global_data/'
logF: 'experiments/lcsts/'
epoch: 20
batch_size: 2
optim: 'adam'
cell: 'lstm'
attention: 'self_att'
learning_rate: 0.0003
max_grad_norm: 10
learning_rate_decay: 0.5
start_decay_at: 6
emb_size: 512
hidden_size: 512
dec_num_layers: 3
enc_num_layers: 3
bidirectional: True
bi_dec: False
dropout: 0.0
max_time_step: 50
eval_interval: 1
save_interval: 3000
metrics: ['rouge']
shared_vocab: True
beam_size: 10
unk: True
schedule: False
selfatt: True
schesamp: False
swish: False
length_norm: True
